# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: kevingayng72@gmail.com
author_name: Kevin Yang
has_binder: false
has_settings: false
kind: frontend
labextension_name: syntax_highlighting
project_short_description: A Jupyter Notebook extension
python_name: syntax_highlighting
repository: https://github.com/NEU-Coop-2024/syntax_highlighting.git
test: false

